### ISSUE TITLE
I would like to colaborate with you

### ISSUE THREAD

**Issue by cyberhax1** [vfedotovs/sslv_web_scraper#248]
Hey!

Found this tool and would like you to help with this tool, if you are interested in helping please leave a email, i could write detailed information. We need scraping for specific section only the new ads. We can communicate in Latvian Also.

Thanks!!

**Comment by vfedotovs** [comment]
Please feel free to send feedback or suggestions on  vfedotovs@outlook.com. You are more than welcom to submit new issues/bug reports or submit Pull requests.
